# Generated by Django 4.2.3 on 2023-07-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
